#theme: minima
title: "ghost.shell"
author: "m4rv4x"
remote_theme: "jeffreytse/jekyll-theme-yat"
email: "m4rv4x@protonmail.com"
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"
description: "Shell hacking ressources"

plugins: [jekyll-paginate]
permalink: /:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

yat:
  date_format: "%b %d, %Y"

defaults:
  home:
    heading: "Cyber Warrior Chronicles"
    subheading: "Unleashing the Digital Arsenal: Exploring the Art of Tactical Hacking"

banner:
  video: https://vjs.zencdn.net/v/oceans.mp4
  loop: true
  volume: 0.8
  start_at: 8.5
  image: https://bit.ly/3xTmdUP
  opacity: 0.618
  background: "#000"
  height: "100vh"
  min_height: "38vh"
  heading_style: "font-size: 4.25em; font-weight: bold; text-decoration: underline"
  subheading_style: "color: gold"

night_mode: "auto"

# Excerpt settings
# excerpt:
#   default_image: /assets/images/default-image.jpeg  # Default image when the image style is not none
#   image_style: z          # Image layout style (It's value could be none, left, right, top, z, z-reverse)
#   image_width: 38.2%      # Image default width
#   image_height: 160px     # Image default height
#   text_size: 350          # Words default size

# Photo previewer settings (PhotoSwipe 5)
# the options please refer to: https://photoswipe.com/options/
# photo_previewer:
#  gallery: "section.main"
#  children: "a.photo-swipe"
#  bgOpacity: 0.8
#  padding:
#    top: 20
#    bottom: 40
#    left: 100
#    right: 100

# Click to top settings
# click_to_top:
#   light:
#     background_color: "white"
#     color: "#454545"
#   dark:
#     background_color: "#34323d"
#     color: "#bbb"

# Disqus comments
# disqus:
#   shortname: "Your Disqus username"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Utterances comments
# See https://utteranc.es/
# set follow_site_theme true to make utterances' theme follow the site's

# utterances:
#   repo: "owner/repo"
#   issue_term: "title"
#   label: "utterances comment"
#   theme: "github-light"
#   follow_site_theme: true

# Build settings
# highlighter: none
markdown: kramdown
kramdown:
  input: GFM

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jekyll-paginate
#  - jekyll-spaceship
